apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-csp-adapter-cluster-role
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - neuvector.com
  resources:
  - neuvectorusagerecords
  resourceNames:
  - neuvector-usage
  verbs:
  - get
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-csp-usages
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - neuvector.com
  resources:
  - neuvectorusagerecords
  verbs:
  - get
  - create
  - update
  - delete
