apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: neuvector-csp-adapter-binding
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: neuvector-csp-adapter-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.awsbilling.serviceAccount }}
    namespace: {{ .Release.Namespace }}
