apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
 name: neuvectorusagerecords.neuvector.com
spec:
 group: neuvector.com
 names:
   plural: neuvectorusagerecords
   singular: neuvectorusagerecord
   kind: NeuvectorUsageRecord
   shortNames:
   - nur
 scope: Cluster
 versions:
   - name: v1
     served: true
     storage: true
     schema:
       openAPIV3Schema:
         type: object
         properties:
           managed_node_count:
             type: integer
           reporting_time:
             type: string
         required:
           - managed_node_count
           - reporting_time 
