name: csp-billing-adapter
apiVersion: v1
version: 0.0.1
appVersion: 0.0.1
description: Helm chart for NeuVector's CSP Billing Adapter
home: https://neuvector.com
icon: https://avatars2.githubusercontent.com/u/19367275?s=200&v=4
maintainers:
  - name: becitsthere
    email: support@neuvector.com
engine: gotpl
